In [ ]:
# from data/train-00000-of-00001-8b4da49264116bbf.parquet create dataframe
import pandas as pd

df = pd.read_parquet('data/train-00000-of-00001-8b4da49264116bbf.parquet')

In [2]:
display(df.head())

,task_url,task_name,task_description,language_url,language_name,code
0,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#ALGOL_68,ALGOL 68,BEGIN # find all primes with strictly increasi...
1,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#Arturo,Arturo,ascending?: function [x][\n initial: digits...
2,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#AWK,AWK,\n# syntax: GAWK -f ASCENDING_PRIMES.AWK\nBEG...
3,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#F.23,F#,\n// Ascending primes. Nigel Galloway: April ...
4,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#Factor,Factor,USING: grouping math math.combinatorics math.f...

In [4]:
# select rows by language_name column equals to 'Prolog'
df_prolog = df[df['language_name'] == 'Prolog']
display(df_prolog)

,task_url,task_name,task_description,language_url,language_name,code
170,http://rosettacode.org/wiki/Array_concatenation,Array concatenation,Task\n\nShow how to concatenate two arrays in ...,#Prolog,Prolog,"\n?- append([1,2,3],[4,5,6],R).\nR = [1, 2, 3..."
413,http://rosettacode.org/wiki/Array_length,Array length,Task\n\nDetermine the amount of elements in an...,#Prolog,Prolog,"| ?- length([""apple"", ""orange""], X).\n \nX = 2..."
603,http://rosettacode.org/wiki/Arithmetic/Integer,Arithmetic/Integer,\nBasic Data Operation\n\nThis is a basic data...,#Prolog,Prolog,"\n \nprint_expression_and_result(M, N, Operat..."
1134,http://rosettacode.org/wiki/Arithmetic-geometr...,Arithmetic-geometric mean,\n\n This page uses content from Wikipedia. Th...,#Prolog,Prolog,"\nagm(A,G,A) :- abs(A-G) < 1.0e-15, !.\nagm(A..."
1270,http://rosettacode.org/wiki/Arithmetic/Rational,Arithmetic/Rational,Task\n\nCreate a reasonably complete implement...,#Prolog,Prolog,"\ndivisor(N, Div) :-\n Max is floor(sqrt(N..."
...,...,...,...,...,...,...
78377,http://rosettacode.org/wiki/24_game/Solve,24 game/Solve,task\n\nWrite a program that takes four digits...,#Prolog,Prolog,"play24(Len, Range, Goal) :-\n\tgame(Len, Range..."
78515,http://rosettacode.org/wiki/2048,2048,Task\n\nImplement a 2D sliding block puzzle ga...,#Prolog,Prolog,/* -------------------------------------------...
78562,http://rosettacode.org/wiki/ABC_problem,ABC problem,ABC problem\n\nYou are encouraged to solve thi...,#Prolog,Prolog,"abc_problem :-\n\tmaplist(abc_problem, ['', 'A..."
78616,http://rosettacode.org/wiki/24_game,24 game,The 24 Game tests one's mental arithmetic.\n\n...,#Prolog,Prolog,:- initialization(main).\n \n \nanswer(24).\np...
78896,http://rosettacode.org/wiki/A%2BB,A+B,A+B ─── a classic problem in programming con...,#Prolog,Prolog,"plus :-\n read_line_to_codes(user_input,X),..."

In [ ]:
# from df_prolog select rows where task_name column is in a list from txt file
task_names = []
with open('data/task_names_preprocessed.txt') as f:
    task_names = f.read().splitlines()

df_prolog_task_names = df_prolog[df_prolog['task_name'].isin(task_names)]
display(df_prolog_task_names)

,task_url,task_name,task_description,language_url,language_name,code
170,http://rosettacode.org/wiki/Array_concatenation,Array concatenation,Task\n\nShow how to concatenate two arrays in ...,#Prolog,Prolog,"\n?- append([1,2,3],[4,5,6],R).\nR = [1, 2, 3..."
413,http://rosettacode.org/wiki/Array_length,Array length,Task\n\nDetermine the amount of elements in an...,#Prolog,Prolog,"| ?- length([""apple"", ""orange""], X).\n \nX = 2..."
603,http://rosettacode.org/wiki/Arithmetic/Integer,Arithmetic/Integer,\nBasic Data Operation\n\nThis is a basic data...,#Prolog,Prolog,"\n \nprint_expression_and_result(M, N, Operat..."
1134,http://rosettacode.org/wiki/Arithmetic-geometr...,Arithmetic-geometric mean,\n\n This page uses content from Wikipedia. Th...,#Prolog,Prolog,"\nagm(A,G,A) :- abs(A-G) < 1.0e-15, !.\nagm(A..."
1270,http://rosettacode.org/wiki/Arithmetic/Rational,Arithmetic/Rational,Task\n\nCreate a reasonably complete implement...,#Prolog,Prolog,"\ndivisor(N, Div) :-\n Max is floor(sqrt(N..."
...,...,...,...,...,...,...
78377,http://rosettacode.org/wiki/24_game/Solve,24 game/Solve,task\n\nWrite a program that takes four digits...,#Prolog,Prolog,"play24(Len, Range, Goal) :-\n\tgame(Len, Range..."
78515,http://rosettacode.org/wiki/2048,2048,Task\n\nImplement a 2D sliding block puzzle ga...,#Prolog,Prolog,/* -------------------------------------------...
78562,http://rosettacode.org/wiki/ABC_problem,ABC problem,ABC problem\n\nYou are encouraged to solve thi...,#Prolog,Prolog,"abc_problem :-\n\tmaplist(abc_problem, ['', 'A..."
78616,http://rosettacode.org/wiki/24_game,24 game,The 24 Game tests one's mental arithmetic.\n\n...,#Prolog,Prolog,:- initialization(main).\n \n \nanswer(24).\np...
78896,http://rosettacode.org/wiki/A%2BB,A+B,A+B ─── a classic problem in programming con...,#Prolog,Prolog,"plus :-\n read_line_to_codes(user_input,X),..."