In [1]:
# from data/train-00000-of-00001-8b4da49264116bbf.parquet create dataframe
import pandas as pd

df = pd.read_parquet('data/train-00000-of-00001-8b4da49264116bbf.parquet')

In [2]:
display(df.head())

,task_url,task_name,task_description,language_url,language_name,code
0,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#ALGOL_68,ALGOL 68,BEGIN # find all primes with strictly increasi...
1,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#Arturo,Arturo,ascending?: function [x][\n initial: digits...
2,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#AWK,AWK,\n# syntax: GAWK -f ASCENDING_PRIMES.AWK\nBEG...
3,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#F.23,F#,\n// Ascending primes. Nigel Galloway: April ...
4,http://rosettacode.org/wiki/Ascending_primes,Ascending primes,Generate and show all primes with strictly asc...,#Factor,Factor,USING: grouping math math.combinatorics math.f...

In [3]:
# select rows by language_name column equals to 'Prolog'
df_prolog = df[df['language_name'] == 'Prolog']
display(df_prolog)

,task_url,task_name,task_description,language_url,language_name,code
170,http://rosettacode.org/wiki/Array_concatenation,Array concatenation,Task\n\nShow how to concatenate two arrays in ...,#Prolog,Prolog,"\n?- append([1,2,3],[4,5,6],R).\nR = [1, 2, 3..."
413,http://rosettacode.org/wiki/Array_length,Array length,Task\n\nDetermine the amount of elements in an...,#Prolog,Prolog,"| ?- length([""apple"", ""orange""], X).\n \nX = 2..."
603,http://rosettacode.org/wiki/Arithmetic/Integer,Arithmetic/Integer,\nBasic Data Operation\n\nThis is a basic data...,#Prolog,Prolog,"\n \nprint_expression_and_result(M, N, Operat..."
1134,http://rosettacode.org/wiki/Arithmetic-geometr...,Arithmetic-geometric mean,\n\n This page uses content from Wikipedia. Th...,#Prolog,Prolog,"\nagm(A,G,A) :- abs(A-G) < 1.0e-15, !.\nagm(A..."
1270,http://rosettacode.org/wiki/Arithmetic/Rational,Arithmetic/Rational,Task\n\nCreate a reasonably complete implement...,#Prolog,Prolog,"\ndivisor(N, Div) :-\n Max is floor(sqrt(N..."
...,...,...,...,...,...,...
78377,http://rosettacode.org/wiki/24_game/Solve,24 game/Solve,task\n\nWrite a program that takes four digits...,#Prolog,Prolog,"play24(Len, Range, Goal) :-\n\tgame(Len, Range..."
78515,http://rosettacode.org/wiki/2048,2048,Task\n\nImplement a 2D sliding block puzzle ga...,#Prolog,Prolog,/* -------------------------------------------...
78562,http://rosettacode.org/wiki/ABC_problem,ABC problem,ABC problem\n\nYou are encouraged to solve thi...,#Prolog,Prolog,"abc_problem :-\n\tmaplist(abc_problem, ['', 'A..."
78616,http://rosettacode.org/wiki/24_game,24 game,The 24 Game tests one's mental arithmetic.\n\n...,#Prolog,Prolog,:- initialization(main).\n \n \nanswer(24).\np...
78896,http://rosettacode.org/wiki/A%2BB,A+B,A+B ─── a classic problem in programming con...,#Prolog,Prolog,"plus :-\n read_line_to_codes(user_input,X),..."

In [4]:
# from df_prolog select rows where task_name column is in a list from txt file
task_names = []

with open('data/task_names_preprocessed.txt') as f:
    task_names = f.read().splitlines()
    df_prolog_task_description = df_prolog['task_description']

df_prolog_task_names = df_prolog[df_prolog['task_name'].isin(task_names)]
display(df_prolog_task_names)

,task_url,task_name,task_description,language_url,language_name,code
7737,http://rosettacode.org/wiki/Towers_of_Hanoi,Towers of Hanoi,Task\n\nSolve the Towers of Hanoi problem ...,#Prolog,Prolog,"hanoi(N) :- move(N,left,center,right).\n \nmov..."
11892,http://rosettacode.org/wiki/Sudoku,Sudoku,Task\n\nSolve a partially filled-in normal 9...,#Prolog,Prolog,:- use_module(library(clpfd)).\n \nsudoku(Rows...
15364,http://rosettacode.org/wiki/Sorting_algorithms...,Sorting algorithms/Merge sort,\nSorting Algorithm\n\nThis is a sorting algor...,#Prolog,Prolog,"% msort( L, S )\n% True if S is a sorted copy ..."
15408,http://rosettacode.org/wiki/Sorting_algorithms...,Sorting algorithms/Quicksort,\nSorting Algorithm\n\nThis is a sorting algor...,#Prolog,Prolog,"qsort( [], [] ).\nqsort( [H|U], S ) :- splitBy..."
20709,http://rosettacode.org/wiki/Sieve_of_Eratosthenes,Sieve of Eratosthenes,This task has been clarified. Its programming ...,#Prolog,Prolog,"primes(N, L) :- numlist(2, N, Xs),\n\t ..."
22079,http://rosettacode.org/wiki/Roman_numerals/Decode,Roman numerals/Decode,Task\n\nCreate a function that takes a Roman n...,#Prolog,Prolog,"decode_digit(i, 1).\ndecode_digit(v, 5).\ndeco..."
22576,http://rosettacode.org/wiki/Roman_numerals/Encode,Roman numerals/Encode,Task\n\nCreate a function taking a positive in...,#Prolog,Prolog,:- use_module(library(clpfd)).\n \nroman :-\n\...
26437,http://rosettacode.org/wiki/Pythagorean_triples,Pythagorean triples,A Pythagorean triple is defined as three posit...,#Prolog,Prolog,"\nshow :-\n Data = [100, 1_000, 10_000, 10..."
27474,http://rosettacode.org/wiki/Prime_decomposition,Prime decomposition,The prime decomposition of a number is defined...,#Prolog,Prolog,"prime_decomp(N, L) :-\n SN is sqrt(N),\n ..."
31193,http://rosettacode.org/wiki/Palindrome_detection,Palindrome detection,A palindrome is a phrase which reads the same ...,#Prolog,Prolog,"palindrome(Word) :- name(Word,List), reverse(L..."
34306,http://rosettacode.org/wiki/N-queens_problem,N-queens problem,\n\nSolve the eight queens puzzle.\n\n\n\nYou ...,#Prolog,Prolog,solution([]).\n \nsolution([X/Y|Others]) :-\n ...
40275,http://rosettacode.org/wiki/Longest_common_sub...,Longest common subsequence,Introduction\n\nDefine a subsequence to be any...,#Prolog,Prolog,"test :-\n time(lcs(""thisisatest"", ""testing1..."
42393,http://rosettacode.org/wiki/Levenshtein_distance,Levenshtein distance,\n\n This page uses content from Wikipedia. Th...,#Prolog,Prolog,"levenshtein(S, T, R) :-\n\tlength(S, M),\n\tM1..."
43570,http://rosettacode.org/wiki/Knight%27s_tour,Knight's tour,\nTask\nProblem: you have a standard 8x8 chess...,#Prolog,Prolog,% N is the number of lines of the chessboard\n...
43657,http://rosettacode.org/wiki/Knapsack_problem/0-1,Knapsack problem/0-1,A tourist wants to make a good trip at the wee...,#Prolog,Prolog,:- use_module(library(clpfd)).\n \nknapsack :-...
47330,http://rosettacode.org/wiki/Huffman_coding,Huffman coding,Huffman encoding is a way to assign binary cod...,#Prolog,Prolog,huffman :-\n\tL = 'this is an example for huff...
51235,http://rosettacode.org/wiki/Greatest_common_di...,Greatest common divisor,Greatest common divisor\n\nYou are encouraged ...,#Prolog,Prolog,"gcd(X, 0, X):- !.\ngcd(0, X, X):- !.\ngcd(X, Y..."
53887,http://rosettacode.org/wiki/Floyd-Warshall_alg...,Floyd-Warshall algorithm,The Floyd–Warshall algorithm is an algorithm f...,#Prolog,Prolog,":- use_module(library(clpfd)).\n \npath(List, ..."
58084,http://rosettacode.org/wiki/Fibonacci_sequence,Fibonacci sequence,The Fibonacci sequence is a sequence Fn ...,#Prolog,Prolog,"\nfib(1, 1) :- !.\nfib(0, 0) :- !.\nfib(N, Va..."
59597,http://rosettacode.org/wiki/Factorial,Factorial,Definitions\n\n The factorial of 0 (zero...,#Prolog,Prolog,"fact(X, 1) :- X<2.\nfact(X, F) :- Y is X-1, fa..."
62458,http://rosettacode.org/wiki/Dijkstra%27s_algor...,Dijkstra's algorithm,This task has been clarified. Its programming ...,#Prolog,Prolog,"rpath([target|reversed_path], distance)"
71358,http://rosettacode.org/wiki/Caesar_cipher,Caesar cipher,"\n\nTask\n\nImplement a Caesar cipher, both en...",#Prolog,Prolog,:- use_module(library(clpfd)).\n \ncaesar :-\n...
72997,http://rosettacode.org/wiki/Binary_search,Binary search,A binary search divides a range of values into...,#Prolog,Prolog,"bin_search(Elt,List,Result):-\n length(List,N..."
75284,http://rosettacode.org/wiki/Balanced_brackets,Balanced brackets,Task:\n\n Generate a string with N opening...,#Prolog,Prolog,"rosetta_brackets :-\n\ttest_brackets([]),\n\tt..."
77645,http://rosettacode.org/wiki/Ackermann_function,Ackermann function,The Ackermann function is a classic example of...,#Prolog,Prolog,:- table ack/3. % memoization reduces the exec...
78616,http://rosettacode.org/wiki/24_game,24 game,The 24 Game tests one's mental arithmetic.\n\n...,#Prolog,Prolog,:- initialization(main).\n \n \nanswer(24).\np...

In [5]:
import pandas as pd

# Define the 30 selected task names
selected_tasks = [
    "Fibonacci sequence",
    "Sieve of Eratosthenes",
    "Sorting algorithms/Quicksort",
    "Binary search",
    "Greatest common divisor",
    "Factorial",
    "Towers of Hanoi",
    "Palindrome detection",
    "Prime decomposition",
    "Dijkstra's algorithm",
    "Levenshtein distance",
    "N-queens problem",
    "Caesar cipher",
    "Ackermann function",
    "Balanced brackets",
    "Knight's tour",
    "Sorting algorithms/Merge sort",
    "Floyd-Warshall algorithm",
    "Roman numerals/Encode",
    "Roman numerals/Decode",
    "Longest common subsequence",
    "Knapsack problem/0-1",
    "Sudoku",
    "Pythagorean triples",
    "Huffman coding",
    "24 game"
]

# Define test inputs for each task
test_inputs = {
    "Fibonacci sequence": [
        "?- time(fib(20, F)).",
        "?- fib(10, F)."
    ],
    "Sieve of Eratosthenes": [
        "?- time(sieve_of_eratosthenes(100, Primes)).",
        "?- sieve_of_eratosthenes(30, Primes)."
    ],
    "Sorting algorithms/Quicksort": [
        "?- time(quicksort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], Sorted)).",
        "?- quicksort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sorted)."
    ],
    "Binary search": [
        "?- time(binary_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 7, Position)).",
        "?- binary_search([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 55, Position)."
    ],
    "Greatest common divisor": [
        "?- time(gcd(1071, 462, GCD)).",
        "?- gcd(35, 49, GCD)."
    ],
    "Factorial": [
        "?- time(factorial(10, F)).",
        "?- factorial(5, F)."
    ],
    "Towers of Hanoi": [
        "?- time(hanoi(4, left, middle, right, Moves)).",
        "?- hanoi(3, a, b, c, Moves)."
    ],
    "Palindrome detection": [
        "?- time(is_palindrome(\"racecar\")).",
        "?- is_palindrome(\"A man a plan a canal Panama\")."
    ],
    "Prime decomposition": [
        "?- time(prime_factors(60, Factors)).",
        "?- prime_factors(123456, Factors)."
    ],
    "Dijkstra's algorithm": [
        "?- time(shortest_path(a, e, Path, Cost)).",
        "?- shortest_path(start, goal, Path, Cost)."
    ],
    "Levenshtein distance": [
        "?- time(levenshtein_distance(\"kitten\", \"sitting\", Distance)).",
        "?- levenshtein_distance(\"book\", \"back\", Distance)."
    ],
    "N-queens problem": [
        "?- time(n_queens(8, Queens)).",
        "?- n_queens(4, Queens)."
    ],
    "Caesar cipher": [
        "?- time(caesar_cipher(\"ATTACK AT DAWN\", 3, Encrypted)).",
        "?- caesar_cipher(\"HELLO WORLD\", 13, Encrypted)."
    ],
    "Ackermann function": [
        "?- time(ackermann(3, 1, Result)).",
        "?- ackermann(2, 3, Result)."
    ],
    "Balanced brackets": [
        "?- time(balanced(\"({[]})\")).",
        "?- balanced(\"([)])\"."
    ],
    "Knight's tour": [
        "?- time(knights_tour(1, 1, Tour)).",
        "?- knights_tour(3, 3, Tour)."
    ],
    "Sorting algorithms/Merge sort": [
        "?- time(merge_sort([38, 27, 43, 3, 9, 82, 10], Sorted)).",
        "?- merge_sort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sorted)."
    ],
    "Floyd-Warshall algorithm": [
        "?- time(floyd_warshall(Distances)).",
        "?- floyd_warshall(Graph, ShortestPaths)."
    ],
    "Roman numerals/Encode": [
        "?- time(to_roman(1999, Roman)).",
        "?- to_roman(42, Roman)."
    ],
    "Roman numerals/Decode": [
        "?- time(from_roman(\"MCMXCIX\", Number)).",
        "?- from_roman(\"XLII\", Number)."
    ],
    "Longest common subsequence": [
        "?- time(lcs(\"ABCDGH\", \"AEDFHR\", LCS)).",
        "?- lcs(\"AGGTAB\", \"GXTXAYB\", LCS)."
    ],
    "Knapsack problem/0-1": [
        "?- time(knapsack([(10,60), (20,100), (30,120)], 50, Value, Items)).",
        "?- knapsack([(2,3), (3,4), (4,5), (5,6)], 5, Value, Items)."
    ],
    "Sudoku": [
        "?- time(sudoku(Puzzle, Solution)).",
        "?- sudoku([5,3,0,0,7,0,0,0,0,6,0,0,1,9,5,0,0,0,0,9,8,0,0,0,0,6,0,8,0,0,0,6,0,0,0,3,4,0,0,8,0,3,0,0,1,7,0,0,0,2,0,0,0,6,0,6,0,0,0,0,2,8,0,0,0,0,4,1,9,0,0,5,0,0,0,0,8,0,0,7,9], Solution)."
    ],
    "Pythagorean triples": [
        "?- time(pythagorean_triples(20, Triples)).",
        "?- pythagorean_triples(10, Triples)."
    ],
    "Huffman coding": [
        "?- time(huffman_coding(\"abracadabra\", Codes)).",
        "?- huffman_coding(\"hello world\", Codes)."
    ],
    "24 game": [
        "?- Digits: [9,4,6,9] 46*9-9+",
        "?- Digits: [7,4,7,8] 8 4 7 7 / - *"
    ]
}

In [6]:
# Function to extract descriptions and code from original dataframe
def create_prolog_tasks_dataframe(df_prolog, selected_tasks, test_inputs):
    # Initialize lists to store data
    data = []
    
    # Loop through selected tasks
    for task in selected_tasks:
        # Try to find the task in the dataframe
        task_row = df_prolog[df_prolog['task_name'] == task]
        
        if not task_row.empty:
            # Get description and code from the dataframe
            description = task_row['task_description'].values[0]
            code = task_row['code'].values[0] if 'code' in df_prolog.columns else "Code not available"
            
            # Get test inputs
            test_input_1 = test_inputs[task][0] if task in test_inputs else ""
            test_input_2 = test_inputs[task][1] if task in test_inputs else ""
            
            # Add to data list
            data.append({
                'task_name': task,
                'task_description': description,
                'code': code,
                'test_input_1': test_input_1,
                'test_input_2': test_input_2
            })
        else:
            # Task not found in dataframe
            print(f"Warning: Task '{task}' not found in the dataframe")
            
            # Add with empty description and code
            data.append({
                'task_name': task,
                'task_description': "Description not available",
                'code': "Code not available",
                'test_input_1': test_inputs[task][0] if task in test_inputs else "",
                'test_input_2': test_inputs[task][1] if task in test_inputs else ""
            })
    
    # Create DataFrame
    return pd.DataFrame(data)

In [7]:
dataset = create_prolog_tasks_dataframe(df_prolog, selected_tasks, test_inputs)
dataset.to_csv('dataset.csv')

In [8]:
dataset

,task_name,task_description,code,test_input_1,test_input_2
0,Fibonacci sequence,The Fibonacci sequence is a sequence Fn ...,"\nfib(1, 1) :- !.\nfib(0, 0) :- !.\nfib(N, Va...","?- time(fib(20, F)).","?- fib(10, F)."
1,Sieve of Eratosthenes,This task has been clarified. Its programming ...,"primes(N, L) :- numlist(2, N, Xs),\n\t ...","?- time(sieve_of_eratosthenes(100, Primes)).","?- sieve_of_eratosthenes(30, Primes)."
2,Sorting algorithms/Quicksort,\nSorting Algorithm\n\nThis is a sorting algor...,"qsort( [], [] ).\nqsort( [H|U], S ) :- splitBy...","?- time(quicksort([3, 1, 4, 1, 5, 9, 2, 6, 5, ...","?- quicksort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sort..."
3,Binary search,A binary search divides a range of values into...,"bin_search(Elt,List,Result):-\n length(List,N...","?- time(binary_search([1, 2, 3, 4, 5, 6, 7, 8,...","?- binary_search([10, 20, 30, 40, 50, 60, 70, ..."
4,Greatest common divisor,Greatest common divisor\n\nYou are encouraged ...,"gcd(X, 0, X):- !.\ngcd(0, X, X):- !.\ngcd(X, Y...","?- time(gcd(1071, 462, GCD)).","?- gcd(35, 49, GCD)."
5,Factorial,Definitions\n\n The factorial of 0 (zero...,"fact(X, 1) :- X<2.\nfact(X, F) :- Y is X-1, fa...","?- time(factorial(10, F)).","?- factorial(5, F)."
6,Towers of Hanoi,Task\n\nSolve the Towers of Hanoi problem ...,"hanoi(N) :- move(N,left,center,right).\n \nmov...","?- time(hanoi(4, left, middle, right, Moves)).","?- hanoi(3, a, b, c, Moves)."
7,Palindrome detection,A palindrome is a phrase which reads the same ...,"palindrome(Word) :- name(Word,List), reverse(L...","?- time(is_palindrome(""racecar"")).","?- is_palindrome(""A man a plan a canal Panama"")."
8,Prime decomposition,The prime decomposition of a number is defined...,"prime_decomp(N, L) :-\n SN is sqrt(N),\n ...","?- time(prime_factors(60, Factors)).","?- prime_factors(123456, Factors)."
9,Dijkstra's algorithm,This task has been clarified. Its programming ...,"rpath([target|reversed_path], distance)","?- time(shortest_path(a, e, Path, Cost)).","?- shortest_path(start, goal, Path, Cost)."
10,Levenshtein distance,\n\n This page uses content from Wikipedia. Th...,"levenshtein(S, T, R) :-\n\tlength(S, M),\n\tM1...","?- time(levenshtein_distance(""kitten"", ""sittin...","?- levenshtein_distance(""book"", ""back"", Distan..."
11,N-queens problem,\n\nSolve the eight queens puzzle.\n\n\n\nYou ...,solution([]).\n \nsolution([X/Y|Others]) :-\n ...,"?- time(n_queens(8, Queens)).","?- n_queens(4, Queens)."
12,Caesar cipher,"\n\nTask\n\nImplement a Caesar cipher, both en...",:- use_module(library(clpfd)).\n \ncaesar :-\n...,"?- time(caesar_cipher(""ATTACK AT DAWN"", 3, Enc...","?- caesar_cipher(""HELLO WORLD"", 13, Encrypted)."
13,Ackermann function,The Ackermann function is a classic example of...,:- table ack/3. % memoization reduces the exec...,"?- time(ackermann(3, 1, Result)).","?- ackermann(2, 3, Result)."
14,Balanced brackets,Task:\n\n Generate a string with N opening...,"rosetta_brackets :-\n\ttest_brackets([]),\n\tt...","?- time(balanced(""({[]})"")).","?- balanced(""([)])""."
15,Knight's tour,\nTask\nProblem: you have a standard 8x8 chess...,% N is the number of lines of the chessboard\n...,"?- time(knights_tour(1, 1, Tour)).","?- knights_tour(3, 3, Tour)."
16,Sorting algorithms/Merge sort,\nSorting Algorithm\n\nThis is a sorting algor...,"% msort( L, S )\n% True if S is a sorted copy ...","?- time(merge_sort([38, 27, 43, 3, 9, 82, 10],...","?- merge_sort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sor..."
17,Floyd-Warshall algorithm,The Floyd–Warshall algorithm is an algorithm f...,":- use_module(library(clpfd)).\n \npath(List, ...",?- time(floyd_warshall(Distances)).,"?- floyd_warshall(Graph, ShortestPaths)."
18,Roman numerals/Encode,Task\n\nCreate a function taking a positive in...,:- use_module(library(clpfd)).\n \nroman :-\n\...,"?- time(to_roman(1999, Roman)).","?- to_roman(42, Roman)."
19,Roman numerals/Decode,Task\n\nCreate a function that takes a Roman n...,"decode_digit(i, 1).\ndecode_digit(v, 5).\ndeco...","?- time(from_roman(""MCMXCIX"", Number)).","?- from_roman(""XLII"", Number)."
20,Longest common subsequence,Introduction\n\nDefine a subsequence to be any...,"test :-\n time(lcs(""thisisatest"", ""testing1...","?- time(lcs(""ABCDGH"", ""AEDFHR"", LCS)).","?- lcs(""AGGTAB"", ""GXTXAYB"", LCS)."
21,Knapsack problem/0-1,A tourist wants to make a good trip at the wee...,:- use_module(library(clpfd)).\n \nknapsack :-...,"?- time(knapsack([(10,60), (20,100), (30,120)]...","?- knapsack([(2,3), (3,4), (4,5), (5,6)], 5, V..."
22,Sudoku,Task\n\nSolve a partially filled-in normal 9...,:- use_module(library(clpfd)).\n \nsudoku(Rows...,"?- time(sudoku(Puzzle, Solution)).","?- sudoku([5,3,0,0,7,0,0,0,0,6,0,0,1,9,5,0,0,0..."
23,Pythagorean triples,A Pythagorean triple is defined as three posit...,"\nshow :-\n Data = [100, 1_000, 10_000, 10...","?- time(pythagorean_triples(20, Triples)).","?- pythagorean_triples(10, Triples)."
24,Huffman coding,Huffman encoding is a way to assign binary cod...,huffman :-\n\tL = 'this is an example for huff...,"?- time(huffman_coding(""abracadabra"", Codes)).","?- huffman_coding(""hello world"", Codes)."
25,24 game,The 24 Game tests one's mental arithmetic.\n\n...,:- initialization(main).\n \n \nanswer(24).\np...,"?- Digits: [9,4,6,9] 46*9-9+","?- Digits: [7,4,7,8] 8 4 7 7 / - *"

In [2]:
from pyswip import Prolog
import pandas as pd
import re

In [3]:
def split_prolog_rules(code):
    """
    Splits a string of multiple Prolog facts and rules by matching
    periods that are not part of a floating-point number. It removes
    any surrounding whitespace from each rule.
    """
    rules = re.split(r'\s*\.(?!\d)\s*', code)
    return [rule for rule in rules if rule]

In [4]:
inter = Prolog()
fibonacci_code = """
fib(1, 1):- !.
fib(0, 0):- !.
fib(N, Value):-
  A is N - 1, fib(A, A1),
  B is N - 2, fib(B, B1),
  Value is A1 + B1.
"""

rules = split_prolog_rules(fibonacci_code)
for rule in rules: 
  inter.assertz(rule)

result = list(inter.query("fib(10,F)"))
result

[{'F': 55}]

In [5]:
result = list(inter.query("fib(11,F)"))
result

[{'F': 89}]

In [1]:
from pyswip import Prolog
import pandas as pd
import re

df = pd.read_csv('data/dataset.csv')

# Add columns for results
df['ground_truth_1'] = ""
df['ground_truth_2'] = ""

for idx, row in df.iterrows():
    task_name = row['task_name']
    code = row['code']
    test_input_1 = row['test_input_1']
    test_input_2 = row['test_input_2']
    
    print(f"Testing {task_name}...")
    
    # Skip if no code
    if code == "Code not available" or pd.isna(code):
        df.at[idx, 'ground_truth_1'] = "No code available"
        df.at[idx, 'ground_truth_2'] = "No code available"
        continue
    
    # Initialize Prolog once per task
    inter = Prolog()
    
    # Split code into rules
    rules = re.split(r'\s*\.\s*(?!\d)', code)
    
    # Load all rules at once
    for rule in rules:
        if rule.strip():
            inter.assertz(rule)

Testing Fibonacci sequence...
Testing Sieve of Eratosthenes...
Testing Sorting algorithms/Quicksort...
Testing Binary search...
Testing Greatest common divisor...
Testing Factorial...
Testing Towers of Hanoi...
Testing Palindrome detection...
Testing Prime decomposition...
Testing Dijkstra's algorithm...
Testing Levenshtein distance...
Testing N-queens problem...
Testing Ackermann function...
Testing Balanced brackets...
Testing Knight's tour...
Testing Sorting algorithms/Merge sort...
Testing Roman numerals/Decode...
Testing Longest common subsequence...
Testing Huffman coding...
Testing 24 game...

In [2]:
for idx, row in df.iterrows():
    task_name = row['task_name']
    code = row['code']
    test_input_1 = row['test_input_1']
    test_input_2 = row['test_input_2']

    print(task_name)
    if task_name == "Sorting algorithms/Merge sort" or task_name == "Huffman coding" or task_name == "24 game":
        continue
    # Test input 1
    if test_input_1 and not pd.isna(test_input_1):
        # Clean query
        query1 = test_input_1.strip()
        if query1.startswith('?-'):
            query1 = query1[2:].strip()
        if query1.endswith('.'):
            query1 = query1[:-1].strip()
        
        # Run query
        print(test_input_1)
        result1 = list(inter.query(query1))
        df.at[idx, 'ground_truth_1'] = str(result1)
    
    # Test input 2
    if test_input_2 and not pd.isna(test_input_2):
        # Clean query
        query2 = test_input_2.strip()
        if query2.startswith('?-'):
            query2 = query2[2:].strip()
        if query2.endswith('.'):
            query2 = query2[:-1].strip()
        
        # Run query
        print(test_input_2)
        result2 = list(inter.query(query2))
        df.at[idx, 'ground_truth_2'] = str(result2)

    df.to_csv('data/prolog_tasks_ground_truth.csv', index=False)

Fibonacci sequence
fib(20, F).
fib(10, F).
Sieve of Eratosthenes
primes(10, Primes).
primes(30, Primes).
Sorting algorithms/Quicksort
qsort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], Sorted).
qsort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sorted).
Binary search
bin_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 7, Position).
bin_search([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 55, Position).
Greatest common divisor
gcd(1071, 462, GCD).
gcd(35, 49, GCD).
Factorial
fact(10, F).
fact(5, F).
Towers of Hanoi
hanoi(4).
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,center,pole,to,left,pole]
[move,a,disk,from,the,center,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,left,pole]
[move,a,disk,from,the,center,pole,to,left,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
hanoi(3).
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,center,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,left,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
Palindrome detection
palindrome("racecar").
palindrome("A man a plan a canal Panama").
Prime decomposition
prime_decomp(60, Factors).
prime_decomp(123456, Factors).
Dijkstra's algorithm
rpath([e,d,c,b,a], 10).
rpath([goal,node3,node2,node1,start], 15).
Levenshtein distance
levenshtein(['k', 'i', 't', 't', 'e', 'n'], ['s', 'i', 't', 't', 'i', 'n', 'g'], Distance).
levenshtein(['b', 'o', 'o', 'k'], ['b', 'a', 'c', 'k'], Distance).
N-queens problem
template(Queens), solution(Queens).
solution([1/4, 2/2, 3/7, 4/3, 5/6, 6/8, 7/5, 8/1]).
Ackermann function
ack(3, 1, Result).
ack(2, 3, Result).
Balanced brackets
test_brackets("({[]})").
test_brackets("([)])").
Knight's tour
knight(1).
  1
  1
  1
  1
  1
  1
  1
knight(3).
  1
Sorting algorithms/Merge sort
Roman numerals/Decode
decode_digit("MCMXCIX", Number).
decode_digit("XLII", Number).
Longest common subsequence
lcs("ABCDGH", "AEDFHR", LCS).
lcs("AGGTAB", "GXTXAYB", LCS).
Huffman coding
24 game