In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "5"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

from unsloth import FastLanguageModel, PatchFastRL
PatchFastRL("GRPO", FastLanguageModel)

from unsloth import is_bfloat16_supported
import torch
max_seq_length = 2048 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

# model, tokenizer = FastLanguageModel.from_pretrained(
#     model_name = "Qwen/Qwen2.5-Coder-3B-Instruct",
#     max_seq_length = max_seq_length,
#     load_in_4bit = True, # False for LoRA 16bit
#     fast_inference = True, # Enable vLLM fast inference
#     max_lora_rank = lora_rank,
#     gpu_memory_utilization = 0.6, # Reduce if out of memory
# )

# model = FastLanguageModel.get_peft_model(
#     model,
#     r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
#     target_modules = [
#         "q_proj", "k_proj", "v_proj", "o_proj",
#         "gate_proj", "up_proj", "down_proj",
#     ], # Remove QKVO if out of memory
#     lora_alpha = lora_rank,
#     use_gradient_checkpointing = "unsloth", # Enable long context finetuning
#     random_state = 3407,
# )

def get_model():
  max_seq_length = 2048 # Can increase for longer reasoning traces
  lora_rank = 32 # Larger rank = smarter, but slower
  # Load base model
  lora_path = "Qwen-3B/checkpoint-3000"
  model, tokenizer = FastLanguageModel.from_pretrained(
      model_name = lora_path,
      max_seq_length = max_seq_length,
      load_in_4bit = True, # False for LoRA 16bit
      fast_inference = True, # Enable vLLM fast inference
      max_lora_rank = lora_rank,
      gpu_memory_utilization = 0.6, # Reduce if out of memory
  )
  model.eval()
  FastLanguageModel.for_inference(model)
  return model, tokenizer

model, tokenizer = get_model()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/home/lab/biancaraimondi/LLM_Format/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🦥 Unsloth Zoo will now patch everything to make training faster!

2025-03-06 18:41:26,805	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

INFO 03-06 18:41:28 __init__.py:207] Automatically detected platform cuda.
==((====))==  Unsloth 2025.2.15: Fast Qwen2 patching. Transformers: 4.49.0.
   \\   /|    GPU: NVIDIA A100-SXM4-80GB. Max memory: 79.151 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.5.1+cu124. CUDA: 8.0. CUDA Toolkit: 12.4. Triton: 3.1.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.28.post3. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/qwen2.5-coder-3b-instruct-bnb-4bit with actual GPU utilization = 59.65%
Unsloth: Your GPU has CUDA compute capability 8.0 with VRAM = 79.15 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 226.
Unsloth: vLLM's KV Cache can use up to 44.91 GB. Also swap space = 6 GB.
INFO 03-06 18:41:42 config.py:549] This model supports multiple tasks: {'reward', 'embed', 'score', 'classify', 'generate'}. Defaulting to 'generate'.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'bfloat16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': [], 'llm_int8_threshold': 6.0}
INFO 03-06 18:41:42 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.3) with config: model='unsloth/qwen2.5-coder-3b-instruct-bnb-4bit', speculative_config=None, tokenizer='unsloth/qwen2.5-coder-3b-instruct-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda:0, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=unsloth/qwen2.5-coder-3b-instruct-bnb-4bit, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":0,"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":232}, use_cached_outputs=False,
INFO 03-06 18:41:43 cuda.py:229] Using Flash Attention backend.
INFO 03-06 18:41:44 model_runner.py:1110] Starting to load model unsloth/qwen2.5-coder-3b-instruct-bnb-4bit...

[W306 18:41:44.783197712 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())

INFO 03-06 18:41:44 loader.py:1089] Loading weights with BitsAndBytes quantization.  May take a while ...
INFO 03-06 18:41:45 weight_utils.py:254] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:03<00:00,  3.06s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:03<00:00,  3.07s/it]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.80it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.80it/s]

INFO 03-06 18:41:49 model_runner.py:1115] Loading model weights took 1.9356 GB
INFO 03-06 18:41:49 punica_selector.py:18] Using PunicaWrapperGPU.
INFO 03-06 18:42:00 worker.py:267] Memory profiling takes 7.79 seconds
INFO 03-06 18:42:00 worker.py:267] the current vLLM instance can use total_gpu_memory (79.15GiB) x gpu_memory_utilization (0.60) = 47.21GiB
INFO 03-06 18:42:00 worker.py:267] model weights take 1.94GiB; non_torch_memory takes 0.09GiB; PyTorch activation peak memory takes 1.24GiB; the rest of the memory reserved for KV Cache is 43.94GiB.
INFO 03-06 18:42:00 executor_base.py:111] # cuda blocks: 79997, # CPU blocks: 10922
INFO 03-06 18:42:00 executor_base.py:116] Maximum concurrency for 2048 tokens per request: 624.98x
INFO 03-06 18:42:11 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes: 100%|██████████| 32/32 [01:00<00:00,  1.90s/it]

INFO 03-06 18:43:12 model_runner.py:1562] Graph capturing finished in 61 secs, took 4.70 GiB
INFO 03-06 18:43:12 llm_engine.py:436] init engine (profile, create kv cache, warmup model) took 80.20 seconds

Unsloth 2025.2.15 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

In [1]:
import re
from datasets import load_dataset, Dataset
import ast
import concurrent
import os
import multiprocessing

# Load and prep dataset
SYSTEM_PROMPT = """
Generate a prolog solution for the asked question.
Follow these steps to craft your response:
1. reason about the given instruction
2. provide a high-quality prolog solution
3. write a query to verify the solution.
Output in the following format:
<reasoning>
...
</reasoning>
<code>
...
</code>
<query>
...
</query>

Write the query just inside <query></query> not in <code></code>.
"""
timeout = 3

def extract_xml_knowledge(text: str) -> str:
    answer = text.split("<code>")[-1]
    answer = answer.split("</code>")[0]
    return answer.strip()

def extract_xml_query(text: str) -> str:
    answer = text.split("<query>")[-1]
    answer = answer.split("</query>")[0]
    return answer.strip()

def split_prolog_rules(code):
    """
    Splits a string of multiple Prolog facts and rules by matching
    periods that are not part of a floating-point number. It removes
    any surrounding whitespace from each rule.
    """
    # This regex splits on a period that is NOT immediately followed by a digit.
    # \s* optionally matches any whitespace before and after the period.
    rules = re.split(r'\s*\.(?!\d)\s*', code)
    # Filter out any empty strings that may occur.
    return [rule for rule in rules if rule]

def parse_kb(prolog_code, query, answer):
    reward = 0
    from pyswip import Prolog
    try:
        prolog_interpreter = Prolog()
        # Filter out any empty rule
        #rules = [rule.strip() for rule in prolog_code.split(").") if rule.strip()]
        #rules = [rule + ")" for rule in rules]
        rules = split_prolog_rules(prolog_code)
        print("-"*20)
        print("rules: ", rules)
        print("-"*20)
        for rule in rules:
            print("Asserting rule: ", rule)
            with concurrent.futures.ThreadPoolExecutor() as executor:
                print("before future")
                future = executor.submit(prolog_interpreter.assertz(rule))
                print("after future")
                try:
                    print("Before result")
                    result = future.result(timeout=timeout)
                    #result = list(future.result(timeout=timeout))
                except concurrent.futures.TimeoutError:
                    print("Query timed out")
                    return 0, None
        
        # Use the instance's query method
        print("Querying: ", query)
        with concurrent.futures.ThreadPoolExecutor() as executor:
            future = executor.submit(prolog_interpreter.query, query)
            try:
                result = future.result(timeout=timeout)
                #result = list(future.result(timeout=timeout))
            except concurrent.futures.TimeoutError:
                print("Query timed out")
                return 0, None
        print("Result: ", result)
        
        for inference in result:
            print("Inference: ", inference)
            for _, result_inference in inference.items():
                print("result_inference: ", result_inference)
                print("Infered: {}, Response: {}, Match: {}".format(result_inference, answer, float(result_inference) == float(answer)))
                try:
                    if float(result_inference) == float(answer):
                        print("Matching!")
                        return 1, result_inference
                except:
                    print("Matching error!")
                    return 0, None
        #print(result)
        # Ensure that the comparison makes sense:
        # This assumes you expect a non-empty result when the answer is correct.
        return 0, None
    except Exception as e:
        print(f"Error encountered: {e}")
        return 0, None

def remove_prolog_comments_and_whitespace(code):
    # Remove block comments (/* ... */)
    code_no_block = re.sub(r'/\*[\s\S]*?\*/', '', code)
    # Remove single-line comments (% ...) from each line
    code_no_comments = re.sub(r'(?m)%.*$', '', code_no_block)
    # Remove newline and tab characters, but keep spaces
    cleaned_code = re.sub(r'[\n\t]', '', code_no_comments)
    return cleaned_code

/home/lab/biancaraimondi/LLM_Format/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# prompt = [{'role': 'system', 'content': SYSTEM_PROMPT},{'role': 'user', 'content': """
# The Fibonacci sequence is a sequence Fn of natural numbers defined recursively:
# F0 = 0 
# F1 = 1 
# Fn = Fn-1 + Fn-2, if n>1
# Task
# Write a function to generate the nth Fibonacci number.
# Solutions can be iterative or recursive (though recursive solutions are generally considered too slow and are mostly used as an exercise in recursion).
# The sequence is sometimes extended into negative numbers by using a straightforward inverse of the positive definition:
# Fn = Fn+2 - Fn+1, if n<0   
# support for negative n in the solution is optional.
# Query the function with n=10."""}]

# text = tokenizer.apply_chat_template(prompt, tokenize = False, add_generation_prompt = True)

# from vllm import SamplingParams
# sampling_params = SamplingParams(
#     temperature = 0.8,
#     top_p = 0.95,
#     max_tokens = 1024,
# )
# output = model.fast_generate(
#     [text],
#     sampling_params = sampling_params,
#     lora_request = None,
# )[0].outputs[0].text

# tmp_code = extract_xml_knowledge(output)
# tmp_code = remove_prolog_comments_and_whitespace(tmp_code)
# print("CODE: ", tmp_code)
# tmp_query = extract_xml_query(output)
# print("QUERY: ", tmp_query)
# tmp_answer = 55
# print("ANSWER: ", tmp_answer)

# _ = parse_kb(tmp_code, tmp_query, tmp_answer)

In [ ]:
# Query the model using data/prolog_tasks_ground_truth.csv
# The dataset contains the following columns:
# Unnamed:, task_name, task_description, code, test_input_1, test_input_2, ground_truth_1, ground_truth_2
import pandas as pd
dataset = pd.read_csv("data/prolog_tasks_ground_truth.csv")
display(dataset.head())

# from vllm import SamplingParams
# sampling_params = SamplingParams(
#     temperature = 0,
#     top_p = 0.000001,
#     max_tokens = 1024,
# )

results_df = pd.DataFrame(columns=['task_name', 'code', 'match_1', 'match_2', 'test_input_1', 'test_input_2', 'result_1', 'result_2', 'ground_truth_1', 'ground_truth_2'])

def process_row(row):
    total_matches = 0
    user_prompt = row[1]['task_description']
    user_prompt = user_prompt + "Query the function with ?- " + row[1]['test_input_1']
    print("-"*20)
    print("USER PROMPT: ", user_prompt)
    print("-"*20)
    prompt = [{'role': 'system', 'content': SYSTEM_PROMPT},{'role': 'user', 'content': user_prompt}]

    # text = tokenizer.apply_chat_template(prompt, tokenize = False, add_generation_prompt = True)

    # output = model.fast_generate(
    #     [text],
    #     sampling_params = sampling_params,
    #     lora_request = None,
    # )[0].outputs[0].text

    # tmp_code = extract_xml_knowledge(output)
    # tmp_code = remove_prolog_comments_and_whitespace(tmp_code)


    tmp_code = row[1]['code']


    print("-"*20)
    print("CODE: ", tmp_code)
    match_1 = 0
    match_2 = 0
    result_1 = None
    result_2 = None
    for i in range(1, 3):
        # tmp_query = extract_xml_query(output)
        # print("-"*20)
        # print("QUERY: ", tmp_query)
        tmp_query = row[1]['test_input_' + str(i)]
        tmp_answer = row[1]['ground_truth_' + str(i)]
        # tmp_answer is a string in the following format "[{'F': 6765}]". Extract the list as [{'F': 6765}]
        tmp_answer = ast.literal_eval(tmp_answer)
        for inference in tmp_answer:
            for _, result_inference in inference.items():
                tmp_answer = result_inference
        print("-"*20)
        print("ANSWER: ", tmp_answer)
        print("-"*20)
        try:
            if i == 1:
                match_1, result_1 = parse_kb(tmp_code, tmp_query, tmp_answer)
            else:
                match_2, result_2 = parse_kb(tmp_code, tmp_query, tmp_answer)
        except Exception as e:
            print("Error encountered: ", e)
    results_df.loc[len(results_df)] = [row[1]['task_name'], tmp_code, match_1, match_2, row[1]['test_input_1'], row[1]['test_input_2'], result_1, result_2, row[1]['ground_truth_1'], row[1]['ground_truth_2']]
    return total_matches

matches = 0
for row in dataset.iterrows():
    print("Processing row: ", row)
    print("Row[1]['task_name']: ", row[1]['task_name'])
    matches += process_row(row)
print("Total matches: ", matches)

,id,task_name,task_description,code,test_input_1,test_input_2,ground_truth_1,ground_truth_2
0,0,Fibonacci sequence,The Fibonacci sequence is a sequence Fn of nat...,"\nfib(1, 1) :- !.\nfib(0, 0) :- !.\nfib(N, Val...","fib(20, F).","fib(10, F).",[{'F': 6765}],[{'F': 55}]
1,1,Sieve of Eratosthenes,\nThe Sieve of Eratosthenes is a simple algori...,"primes(N, L) :- numlist(2, N, Xs),\nsieve(Xs, ...","primes(10, Primes).","primes(30, Primes).","[{'Primes': [2, 3, 5, 7]}]","[{'Primes': [2, 3, 5, 7, 11, 13, 17, 19, 23, 2..."
2,2,Sorting algorithms/Quicksort,\nSorting Algorithm\nThis is a sorting algorit...,"qsort( [], [] ).\nqsort( [H|U], S ) :- splitBy...","qsort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], Sorted).","qsort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sorted).","[{'Sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}]","[{'Sorted': [1, 2, 3, 4, 5, 6, 7, 8, 9]}]"
3,3,Binary search,A binary search divides a range of values into...,% Binary search with correct parameter order\n...,"bin_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 7,...","bin_search([10, 20, 30, 40, 50, 60, 70, 80, 90...",[{'Position': 7}],[]
4,4,Greatest common divisor,Greatest common divisor\nYou are encouraged to...,"gcd(X, 0, X):- !.\ngcd(0, X, X):- !.\ngcd(X, Y...","gcd(1071, 462, GCD).","gcd(35, 49, GCD).",[{'GCD': 21}],[{'GCD': 7}]

Processing row:  (0, id                                                                  0
task_name                                          Fibonacci sequence
task_description    The Fibonacci sequence is a sequence Fn of nat...
code                \nfib(1, 1) :- !.\nfib(0, 0) :- !.\nfib(N, Val...
test_input_1                                              fib(20, F).
test_input_2                                              fib(10, F).
ground_truth_1                                          [{'F': 6765}]
ground_truth_2                                            [{'F': 55}]
Name: 0, dtype: object)
Row[1]['task_name']:  Fibonacci sequence
--------------------
USER PROMPT:  The Fibonacci sequence is a sequence Fn of natural numbers defined recursively:
    F0 = 0
    F1 = 1
    Fn = Fn-1 + Fn-2, if n>1
Task
Write a function to generate the nth Fibonacci number.
Solutions can be iterative or recursive (though recursive solutions are generally considered too slow and are mostly used as an exercise in recursion).
The sequence is sometimes extended into negative numbers by using a straightforward inverse of the positive definition:
    Fn = Fn+2 - Fn+1, if n<0
support for negative n in the solution is optional.
Query the function with ?- fib(20, F).
--------------------
--------------------
CODE:
fib(1, 1) :- !.
fib(0, 0) :- !.
fib(N, Value) :-
  A is N - 1, fib(A, A1),
  B is N - 2, fib(B, B1),
  Value is A1 + B1.

--------------------
ANSWER:  6765
--------------------
--------------------
rules:  ['\nfib(1, 1) :- !', 'fib(0, 0) :- !', 'fib(N, Value) :-\n  A is N - 1, fib(A, A1),\n  B is N - 2, fib(B, B1),\n  Value is A1 + B1']
--------------------
Asserting rule:
fib(1, 1) :- !
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  55
--------------------
--------------------
rules:  ['\nfib(1, 1) :- !', 'fib(0, 0) :- !', 'fib(N, Value) :-\n  A is N - 1, fib(A, A1),\n  B is N - 2, fib(B, B1),\n  Value is A1 + B1']
--------------------
Asserting rule:
fib(1, 1) :- !
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
Processing row:  (1, id                                                                  1
task_name                                       Sieve of Eratosthenes
task_description    \nThe Sieve of Eratosthenes is a simple algori...
code                primes(N, L) :- numlist(2, N, Xs),\nsieve(Xs, ...
test_input_1                                      primes(10, Primes).
test_input_2                                      primes(30, Primes).
ground_truth_1                             [{'Primes': [2, 3, 5, 7]}]
ground_truth_2      [{'Primes': [2, 3, 5, 7, 11, 13, 17, 19, 23, 2...
Name: 1, dtype: object)
Row[1]['task_name']:  Sieve of Eratosthenes
--------------------
USER PROMPT:
The Sieve of Eratosthenes is a simple algorithm that finds the prime numbers up to a given integer.

Task

Implement the Sieve of Eratosthenes algorithm, with the only allowed optimization that the outer loop can stop at the square root of the limit, and the inner loop may start at the square of the prime just found.
That means especially that you shouldn't optimize by using pre-computed wheels, i.e. don't assume you need only to cross out odd numbers (wheel based on 2), numbers equal to 1 or 5 modulo 6 (wheel based on 2 and 3), or similar wheels based on low primes.
If there's an easy way to add such a wheel based optimization, implement it as an alternative version.
Note
It is important that the sieve algorithm be the actual algorithm used to find prime numbers for the task.Query the function with ?- primes(10, Primes).
--------------------
--------------------
CODE:  primes(N, L) :- numlist(2, N, Xs),
sieve(Xs, L).
sieve([H|T], [H|X]) :- H2 is H + H,
filter(H, H2, T, R),
sieve(R, X).
sieve([], []).
filter(_, _, [], []).
filter(H, H2, [H1|T], R) :-
( H1 < H2 -> R = [H1|R1], filter(H, H2, T, R1);
H3 is H2 + H,
( H1 =:= H2  -> filter(H, H3, T, R);filter(H, H3, [H1|T], R) ) ).
--------------------
ANSWER:  [2, 3, 5, 7]
--------------------
--------------------
rules:  ['primes(N, L) :- numlist(2, N, Xs),\nsieve(Xs, L)', 'sieve([H|T], [H|X]) :- H2 is H + H, \nfilter(H, H2, T, R),\nsieve(R, X)', 'sieve([], [])', 'filter(_, _, [], [])', 'filter(H, H2, [H1|T], R) :- \n( H1 < H2 -> R = [H1|R1], filter(H, H2, T, R1);\nH3 is H2 + H,\n( H1 =:= H2  -> filter(H, H3, T, R);filter(H, H3, [H1|T], R) ) )']
--------------------
Asserting rule:  primes(N, L) :- numlist(2, N, Xs),
sieve(Xs, L)
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
--------------------
--------------------
rules:  ['primes(N, L) :- numlist(2, N, Xs),\nsieve(Xs, L)', 'sieve([H|T], [H|X]) :- H2 is H + H, \nfilter(H, H2, T, R),\nsieve(R, X)', 'sieve([], [])', 'filter(_, _, [], [])', 'filter(H, H2, [H1|T], R) :- \n( H1 < H2 -> R = [H1|R1], filter(H, H2, T, R1);\nH3 is H2 + H,\n( H1 =:= H2  -> filter(H, H3, T, R);filter(H, H3, [H1|T], R) ) )']
--------------------
Asserting rule:  primes(N, L) :- numlist(2, N, Xs),
sieve(Xs, L)
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
Processing row:  (2, id                                                                  2
task_name                                Sorting algorithms/Quicksort
task_description    \nSorting Algorithm\nThis is a sorting algorit...
code                qsort( [], [] ).\nqsort( [H|U], S ) :- splitBy...
test_input_1        qsort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], Sorted).
test_input_2              qsort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sorted).
ground_truth_1        [{'Sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}]
ground_truth_2              [{'Sorted': [1, 2, 3, 4, 5, 6, 7, 8, 9]}]
Name: 2, dtype: object)
Row[1]['task_name']:  Sorting algorithms/Quicksort
--------------------
USER PROMPT:
Sorting Algorithm
This is a sorting algorithm. It may be applied to a set of data in order to sort it.

Task

Sort an array (or list) elements using the quicksort algorithm.
The elements must have a strict weak order and the index of the array can be of any discrete type.
For languages where this is not possible, sort an array of integers.
Quicksort, also known as partition-exchange sort, uses these steps.
- Choose any element of the array to be the pivot.
- Divide all other elements (except the pivot) into two partitions.
- All elements less than the pivot must be in the first partition.
- All elements greater than the pivot must be in the second partition.
- Use recursion to sort both partitions.
- Join the first sorted partition, the pivot, and the second sorted partition.
The best pivot creates partitions of equal length (or lengths differing by 1).
The worst pivot creates an empty partition (for example, if the pivot is the first or last element of a sorted array).
The run-time of Quicksort ranges from O(n log n) with the best pivots, to O(n2) with the worst pivots, where n is the number of elements in the array.Query the function with ?- qsort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], Sorted).
--------------------
--------------------
CODE:  qsort( [], [] ).
qsort( [H|U], S ) :- splitBy(H, U, L, R), qsort(L, SL), qsort(R, SR), append(SL, [H|SR], S).
% splitBy( H, U, LS, RS )
% True if LS = { L in U | L <= H }; RS = { R in U | R > H }
splitBy( _, [], [], []).
splitBy( H, [U|T], [U|LS], RS ) :- U =< H, splitBy(H, T, LS, RS).
splitBy( H, [U|T], LS, [U|RS] ) :- U  > H, splitBy(H, T, LS, RS).

--------------------
ANSWER:  [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]
--------------------
--------------------
rules:  ['qsort( [], [] )', 'qsort( [H|U], S ) :- splitBy(H, U, L, R), qsort(L, SL), qsort(R, SR), append(SL, [H|SR], S)', '% splitBy( H, U, LS, RS )\n% True if LS = { L in U | L <= H }; RS = { R in U | R > H }\nsplitBy( _, [], [], [])', 'splitBy( H, [U|T], [U|LS], RS ) :- U =< H, splitBy(H, T, LS, RS)', 'splitBy( H, [U|T], LS, [U|RS] ) :- U  > H, splitBy(H, T, LS, RS)']
--------------------
Asserting rule:  qsort( [], [] )
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
--------------------
--------------------
rules:  ['qsort( [], [] )', 'qsort( [H|U], S ) :- splitBy(H, U, L, R), qsort(L, SL), qsort(R, SR), append(SL, [H|SR], S)', '% splitBy( H, U, LS, RS )\n% True if LS = { L in U | L <= H }; RS = { R in U | R > H }\nsplitBy( _, [], [], [])', 'splitBy( H, [U|T], [U|LS], RS ) :- U =< H, splitBy(H, T, LS, RS)', 'splitBy( H, [U|T], LS, [U|RS] ) :- U  > H, splitBy(H, T, LS, RS)']
--------------------
Asserting rule:  qsort( [], [] )
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
Processing row:  (3, id                                                                  3
task_name                                               Binary search
task_description    A binary search divides a range of values into...
code                % Binary search with correct parameter order\n...
test_input_1        bin_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 7,...
test_input_2        bin_search([10, 20, 30, 40, 50, 60, 70, 80, 90...
ground_truth_1                                      [{'Position': 7}]
ground_truth_2                                                     []
Name: 3, dtype: object)
Row[1]['task_name']:  Binary search
--------------------
USER PROMPT:  A binary search divides a range of values into halves, and continues to narrow down the field of search until the unknown value is found. It is the classic example of a "divide and conquer" algorithm.
As an analogy, consider the children's game "guess a number." The scorer has a secret number, and will only tell the player if their guessed number is higher than, lower than, or equal to the secret number. The player then uses this information to guess a new number.
As the player, an optimal strategy for the general case is to start by choosing the range's midpoint as the guess, and then asking whether the guess was higher, lower, or equal to the secret number. If the guess was too high, one would select the point exactly between the range midpoint and the beginning of the range. If the original guess was too low, one would ask about the point exactly between the range midpoint and the end of the range. This process repeats until one has reached the secret number.

Task

Given the starting point of a range, the ending point of a range, and the "secret value", implement a binary search through a sorted integer array for a certain number. Implementations can be recursive or iterative (both if you can). Print out whether or not the number was in the array afterwards. If it was, print the index also.
There are several binary search algorithms commonly seen. They differ by how they treat multiple values equal to the given value, and whether they indicate whether the element was found or not. For completeness we will present pseudocode for all of them.
All of the following code examples use an "inclusive" upper bound (i.e. high = N-1 initially). Any of the examples can be converted into an equivalent example using "exclusive" upper bound (i.e. high = N initially) by making the following simple changes (which simply increase high by 1):
change high = N-1 to high = N
change high = mid-1 to high = mid
(for recursive algorithm) change if (high < low) to if (high <= low)
(for iterative algorithm) change while (low <= high) to while (low < high)Query the function with ?- bin_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 7, Position).
--------------------
--------------------
CODE:  % Binary search with correct parameter order
bin_search(List, Elt, Result):-
  length(List, N),
  bin_search_inner(Elt, List, 1, N, Result).

bin_search_inner(Elt, List, J, J, J):-
  nth1(J, List, Elt).
bin_search_inner(Elt, List, Begin, End, Mid):-
  Begin < End,
  Mid is (Begin+End) div 2,
  nth1(Mid, List, Elt).
bin_search_inner(Elt, List, Begin, End, Result):-
  Begin < End,
  Mid is (Begin+End) div 2,
  nth1(Mid, List, MidElt),
  MidElt < Elt,
  NewBegin is Mid+1,
  bin_search_inner(Elt, List, NewBegin, End, Result).
bin_search_inner(Elt, List, Begin, End, Result):-
  Begin < End,
  Mid is (Begin+End) div 2,
  nth1(Mid, List, MidElt),
  MidElt > Elt,
  NewEnd is Mid-1,
  bin_search_inner(Elt, List, Begin, NewEnd, Result).
--------------------
ANSWER:  7
--------------------
--------------------
rules:  ['% Binary search with correct parameter order\nbin_search(List, Elt, Result):-\n  length(List, N), \n  bin_search_inner(Elt, List, 1, N, Result)', 'bin_search_inner(Elt, List, J, J, J):-\n  nth1(J, List, Elt)', 'bin_search_inner(Elt, List, Begin, End, Mid):-\n  Begin < End,\n  Mid is (Begin+End) div 2,\n  nth1(Mid, List, Elt)', 'bin_search_inner(Elt, List, Begin, End, Result):-\n  Begin < End,\n  Mid is (Begin+End) div 2,\n  nth1(Mid, List, MidElt),\n  MidElt < Elt,\n  NewBegin is Mid+1,\n  bin_search_inner(Elt, List, NewBegin, End, Result)', 'bin_search_inner(Elt, List, Begin, End, Result):-\n  Begin < End,\n  Mid is (Begin+End) div 2,\n  nth1(Mid, List, MidElt),\n  MidElt > Elt,\n  NewEnd is Mid-1,\n  bin_search_inner(Elt, List, Begin, NewEnd, Result)']
--------------------
Asserting rule:  % Binary search with correct parameter order
bin_search(List, Elt, Result):-
  length(List, N),
  bin_search_inner(Elt, List, 1, N, Result)
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  []
--------------------
--------------------
rules:  ['% Binary search with correct parameter order\nbin_search(List, Elt, Result):-\n  length(List, N), \n  bin_search_inner(Elt, List, 1, N, Result)', 'bin_search_inner(Elt, List, J, J, J):-\n  nth1(J, List, Elt)', 'bin_search_inner(Elt, List, Begin, End, Mid):-\n  Begin < End,\n  Mid is (Begin+End) div 2,\n  nth1(Mid, List, Elt)', 'bin_search_inner(Elt, List, Begin, End, Result):-\n  Begin < End,\n  Mid is (Begin+End) div 2,\n  nth1(Mid, List, MidElt),\n  MidElt < Elt,\n  NewBegin is Mid+1,\n  bin_search_inner(Elt, List, NewBegin, End, Result)', 'bin_search_inner(Elt, List, Begin, End, Result):-\n  Begin < End,\n  Mid is (Begin+End) div 2,\n  nth1(Mid, List, MidElt),\n  MidElt > Elt,\n  NewEnd is Mid-1,\n  bin_search_inner(Elt, List, Begin, NewEnd, Result)']
--------------------
Asserting rule:  % Binary search with correct parameter order
bin_search(List, Elt, Result):-
  length(List, N),
  bin_search_inner(Elt, List, 1, N, Result)
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
Processing row:  (4, id                                                                  4
task_name                                     Greatest common divisor
task_description    Greatest common divisor\nYou are encouraged to...
code                gcd(X, 0, X):- !.\ngcd(0, X, X):- !.\ngcd(X, Y...
test_input_1                                     gcd(1071, 462, GCD).
test_input_2                                        gcd(35, 49, GCD).
ground_truth_1                                          [{'GCD': 21}]
ground_truth_2                                           [{'GCD': 7}]
Name: 4, dtype: object)
Row[1]['task_name']:  Greatest common divisor
--------------------
USER PROMPT:  Greatest common divisor
You are encouraged to solve this task according to the task description, using any language you may know.

Task

Find the greatest common divisor (GCD) of two integers.Greatest common divisor is also known as greatest common factor (gcf) and greatest common measure.Query the function with ?- gcd(1071, 462, GCD).
--------------------
--------------------
CODE:  gcd(X, 0, X):- !.
gcd(0, X, X):- !.
gcd(X, Y, D):- X > Y, !, Z is X mod Y, gcd(Y, Z, D).
gcd(X, Y, D):- Z is Y mod X, gcd(X, Z, D).
--------------------
ANSWER:  21
--------------------
--------------------
rules:  ['gcd(X, 0, X):- !', 'gcd(0, X, X):- !', 'gcd(X, Y, D):- X > Y, !, Z is X mod Y, gcd(Y, Z, D)', 'gcd(X, Y, D):- Z is Y mod X, gcd(X, Z, D)']
--------------------
Asserting rule:  gcd(X, 0, X):- !
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  7
--------------------
--------------------
rules:  ['gcd(X, 0, X):- !', 'gcd(0, X, X):- !', 'gcd(X, Y, D):- X > Y, !, Z is X mod Y, gcd(Y, Z, D)', 'gcd(X, Y, D):- Z is Y mod X, gcd(X, Z, D)']
--------------------
Asserting rule:  gcd(X, 0, X):- !
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
Processing row:  (5, id                                                                  5
task_name                                                   Factorial
task_description    Definitions\nThe factorial of 0 (zero) is defi...
code                fact(X, 1) :- X < 2.\nfact(X, F) :- X >= 2, Y ...
test_input_1                                             fact(10, F).
test_input_2                                              fact(5, F).
ground_truth_1                                       [{'F': 3628800}]
ground_truth_2                                           [{'F': 120}]
Name: 5, dtype: object)
Row[1]['task_name']:  Factorial
--------------------
USER PROMPT:  Definitions
The factorial of 0 (zero) is defined as being 1 (unity).
The Factorial Function of a positive integer, n, is defined as the product of the sequence: n, n-1, n-2, ... 1

Task

Write a function to return the factorial of a number.
Solutions can be iterative or recursive.
Support for trapping negative n errors is optional.Query the function with ?- fact(10, F).
--------------------
--------------------
CODE:  fact(X, 1) :- X < 2.
fact(X, F) :- X >= 2, Y is X-1, fact(Y, Z), F is Z*X.
--------------------
ANSWER:  3628800
--------------------
--------------------
rules:  ['fact(X, 1) :- X < 2', 'fact(X, F) :- X >= 2, Y is X-1, fact(Y, Z), F is Z*X']
--------------------
Asserting rule:  fact(X, 1) :- X < 2
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  120
--------------------
--------------------
rules:  ['fact(X, 1) :- X < 2', 'fact(X, F) :- X >= 2, Y is X-1, fact(Y, Z), F is Z*X']
--------------------
Asserting rule:  fact(X, 1) :- X < 2
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
Processing row:  (6, id                                                                  6
task_name                                             Towers of Hanoi
task_description    Task\nSolve the Towers of Hanoi problem with r...
code                hanoi(N) :- move(N,left,center,right).\nmove(0...
test_input_1                                                hanoi(4).
test_input_2                                                hanoi(3).
ground_truth_1                                   [{'result': 'true'}]
ground_truth_2                                   [{'result': 'true'}]
Name: 6, dtype: object)
Row[1]['task_name']:  Towers of Hanoi
--------------------
USER PROMPT:  Task
Solve the Towers of Hanoi problem with recursion.Query the function with ?- hanoi(4).
--------------------
--------------------
CODE:  hanoi(N) :- move(N,left,center,right).
move(0,_,_,_) :- !.
move(N,A,B,C) :-
    M is N-1,
    move(M,A,C,B),
    inform(A,B),
    move(M,C,B,A).
inform(X,Y) :- write([move,a,disk,from,the,X,pole,to,Y,pole]), nl.
--------------------
ANSWER:  true
--------------------
--------------------
rules:  ['hanoi(N) :- move(N,left,center,right)', 'move(0,_,_,_) :- !', 'move(N,A,B,C) :-\n    M is N-1,\n    move(M,A,C,B),\n    inform(A,B),\n    move(M,C,B,A)', 'inform(X,Y) :- write([move,a,disk,from,the,X,pole,to,Y,pole]), nl']
--------------------
Asserting rule:  hanoi(N) :- move(N,left,center,right)
before future
after future
Before result
Error encountered: 'NoneType' object is not callable
--------------------
ANSWER:  true

AttributeError: 'set' object has no attribute 'items'

In [ ]:
display(results_df)

In [16]:
!pip install pyswip

Defaulting to user installation because normal site-packages is not writeable
Collecting pyswip
  Using cached pyswip-0.3.2-py3-none-any.whl (35 kB)
Installing collected packages: pyswip
Successfully installed pyswip-0.3.2

## Codice di Max per test del codice del dataset

In [26]:
import pandas as pd
import concurrent.futures
import re
import ast
import time
from pyswip import Prolog

In [18]:
dataset = pd.read_csv('data/prolog_tasks_ground_truth.csv')
display(dataset.head())

,id,task_name,task_description,code,test_input_1,test_input_2,ground_truth_1,ground_truth_2
0,0,Fibonacci sequence,The Fibonacci sequence is a sequence Fn of nat...,"\nfib(1, 1) :- !.\nfib(0, 0) :- !.\nfib(N, Val...","fib(20, F).","fib(10, F).",[{'F': 6765}],[{'F': 55}]
1,1,Sieve of Eratosthenes,\nThe Sieve of Eratosthenes is a simple algori...,"primes(N, L) :- numlist(2, N, Xs),\nsieve(Xs, ...","primes(10, Primes).","primes(30, Primes).","[{'Primes': [2, 3, 5, 7]}]","[{'Primes': [2, 3, 5, 7, 11, 13, 17, 19, 23, 2..."
2,2,Sorting algorithms/Quicksort,\nSorting Algorithm\nThis is a sorting algorit...,"qsort( [], [] ).\nqsort( [H|U], S ) :- splitBy...","qsort([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], Sorted).","qsort([9, 8, 7, 6, 5, 4, 3, 2, 1], Sorted).","[{'Sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}]","[{'Sorted': [1, 2, 3, 4, 5, 6, 7, 8, 9]}]"
3,3,Binary search,A binary search divides a range of values into...,% Binary search with correct parameter order\n...,"bin_search([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 7,...","bin_search([10, 20, 30, 40, 50, 60, 70, 80, 90...",[{'Position': 7}],[]
4,4,Greatest common divisor,Greatest common divisor\nYou are encouraged to...,"gcd(X, 0, X):- !.\ngcd(0, X, X):- !.\ngcd(X, Y...","gcd(1071, 462, GCD).","gcd(35, 49, GCD).",[{'GCD': 21}],[{'GCD': 7}]

In [ ]:
import pandas as pd
from pyswip import Prolog
import tempfile
import os

def run_prolog_test(code, test_input):
    with tempfile.NamedTemporaryFile(suffix='.pl', mode='w', delete=False) as temp_file:
        temp_file_path = temp_file.name
        temp_file.write(code)
    
    try:
        prolog = Prolog()
        prolog.consult(temp_file_path)
        
        query_results = list(prolog.query(test_input))
        if not query_results:
            return "false"
        elif query_results == [{}]:
            return "true"
        else:
            return str(query_results)
            
    except Exception as e:
        return f"Error: {str(e)}"
    finally:
        os.unlink(temp_file_path)

def test_all_prolog_code(data_path):
    df = pd.read_csv(data_path)
    
    df['result_1'] = None
    df['result_2'] = None
    df['test_1_passed'] = None
    df['test_2_passed'] = None
    
    for idx, row in df.iterrows():
        print(f"Testing task {idx+1}/{len(df)}: {row['task_name']}")
        
        result_1 = run_prolog_test(row['code'], row['test_input_1'])
        result_2 = run_prolog_test(row['code'], row['test_input_2'])
        
        df.at[idx, 'result_1'] = result_1
        df.at[idx, 'result_2'] = result_2
        

        def normalize_result(value):
            value_str = str(value).lower()
            
            # Handle error cases
            if value_str.startswith("error"):
                return "error"
                
            # Convert Boolean results
            if "result" in value_str and "false" in value_str:
                return "false"
            if "result" in value_str and "true" in value_str:
                return "true"
            if value_str == "true" or value_str == "\"true\"":
                return "true"
            if value_str == "false" or value_str == "\"false\"":
                return "false"
            if value_str == "{true}" or value_str == "[{true}]":
                return "true"
                
            # Normalize dictionary keys in list results
            # Convert patterns like [{'X': 24}] to [{'x': 24}]
            if "[{'" in value_str and "'}]" in value_str:
                # Extract the key
                key_start = value_str.find("[{'") + 3
                key_end = value_str.find("':", key_start)
                if key_start != -1 and key_end != -1:
                    key = value_str[key_start:key_end].lower()
                    # Replace the key with lowercase
                    value_str = value_str.replace(value_str[key_start:key_end], key)
                    
            # Handle LCS case specifically
            if "lcs" in value_str:
                # Normalize spacing in LCS lists
                value_str = value_str.replace(" ", "")
                
            return value_str
            
        norm_ground_truth_1 = normalize_result(row['ground_truth_1'])
        norm_ground_truth_2 = normalize_result(row['ground_truth_2'])
        norm_result_1 = normalize_result(result_1)
        norm_result_2 = normalize_result(result_2)
        
        print(f"Task: {row['task_name']}")
        print(f"GT1: {row['ground_truth_1']} -> {norm_ground_truth_1}")
        print(f"Result1: {result_1} -> {norm_result_1}")
        print(f"Match: {norm_result_1 == norm_ground_truth_1}")
        print("---")
        df.at[idx, 'test_1_passed'] = norm_result_1 == norm_ground_truth_1
        df.at[idx, 'test_2_passed'] = norm_result_2 == norm_ground_truth_2

    return df

In [15]:
results_df = test_all_prolog_code('/home/max/Desktop/UNIBO/LLM_Format/data/prolog_tasks_ground_truth.csv')

Testing task 1/20: Fibonacci sequence
Task: Fibonacci sequence
GT1: [{'F': 6765}] -> [{'f': 6765}]
Result1: [{'F': 6765}] -> [{'f': 6765}]
Match: True
---
Testing task 2/20: Sieve of Eratosthenes
Task: Sieve of Eratosthenes
GT1: [{'Primes': [2, 3, 5, 7]}] -> [{'primes': [2, 3, 5, 7]}]
Result1: [{'Primes': [2, 3, 5, 7]}] -> [{'primes': [2, 3, 5, 7]}]
Match: True
---
Testing task 3/20: Sorting algorithms/Quicksort
Task: Sorting algorithms/Quicksort
GT1: [{'Sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}] -> [{'sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}]
Result1: [{'Sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}] -> [{'sorted': [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]}]
Match: True
---
Testing task 4/20: Binary search
Task: Binary search
GT1: [{'Position': 7}] -> [{'position': 7}]
Result1: [{'Position': 7}] -> [{'position': 7}]
Match: True
---
Testing task 5/20: Greatest common divisor
Task: Greatest common divisor
GT1: [{'GCD': 21}] -> [{'gcd': 21}]
Result1: [{'GCD': 21}] -> [{'gcd': 21}]
Match: True
---
Testing task 6/20: Factorial
Task: Factorial
GT1: [{'F': 3628800}] -> [{'f': 3628800}]
Result1: [{'F': 3628800}] -> [{'f': 3628800}]
Match: True
---
Testing task 7/20: Towers of Hanoi
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,center,pole,to,left,pole]
[move,a,disk,from,the,center,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,left,pole]
[move,a,disk,from,the,center,pole,to,left,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,right,pole]
[move,a,disk,from,the,center,pole,to,right,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
[move,a,disk,from,the,right,pole,to,left,pole]
[move,a,disk,from,the,right,pole,to,center,pole]
[move,a,disk,from,the,left,pole,to,center,pole]
Task: Towers of Hanoi
GT1: [{'result': 'true'}] -> true
Result1: true -> true
Match: True
---
Testing task 8/20: Palindrome detection
Task: Palindrome detection
GT1: [{'result':'true'}] -> true
Result1: true -> true
Match: True
---
Testing task 9/20: Prime decomposition
Task: Prime decomposition
GT1: [{'Factors': [5, 3, 2, 2]}] -> [{'factors': [5, 3, 2, 2]}]
Result1: [{'Factors': [5, 3, 2, 2]}] -> [{'factors': [5, 3, 2, 2]}]
Match: True
---
Testing task 10/20: Dijkstra's algorithm
Task: Dijkstra's algorithm
GT1: [{'result':'true'}] -> true
Result1: true -> true
Match: True
---
Testing task 11/20: Levenshtein distance
Task: Levenshtein distance
GT1: [{'Distance': 3}] -> [{'distance': 3}]
Result1: [{'Distance': 3}] -> [{'distance': 3}]
Match: True
---
Testing task 12/20: N-queens problem
Task: N-queens problem
GT1: [{'result': 'true'}] -> true
Result1: true -> true
Match: True
---
Testing task 13/20: Ackermann function
Task: Ackermann function
GT1: [{'Result': 13}] -> [{'result': 13}]
Result1: [{'Result': 13}] -> [{'result': 13}]
Match: True
---
Testing task 14/20: Balanced brackets
Task: Balanced brackets
GT1: [{'result':'false'}] -> false
Result1: false -> false
Match: True
---
Testing task 15/20: Knight's tour
Task: Knight's tour
GT1: [{'result': 'false'}] -> false
Result1: false -> false
Match: True
---
Testing task 16/20: Sorting algorithms/Merge sort
Task: Sorting algorithms/Merge sort
GT1: [{'Sorted': [1, 2, 3, 4]}] -> [{'sorted': [1, 2, 3, 4]}]
Result1: [{'Sorted': [1, 2, 3, 4]}] -> [{'sorted': [1, 2, 3, 4]}]
Match: True
---
Testing task 17/20: Roman numerals/Decode
Task: Roman numerals/Decode
GT1: [{True}] -> true
Result1: true -> true
Match: True
---
Testing task 18/20: Longest common subsequence
Task: Longest common subsequence
GT1: [{'LCS': ['a','c','e']}] -> [{'lcs':['a','c','e']}]
Result1: [{'LCS': ['a', 'c', 'e']}] -> [{'lcs':['a','c','e']}]
Match: True
---
Testing task 19/20: Huffman coding
Task: Huffman coding
GT1: [{'Result': [[2, 'a'], [1, 'b'], [3, 'c']]}] -> [{'result': [[2, 'a'], [1, 'b'], [3, 'c']]}]
Result1: [{'Result': [[2, 'a'], [1, 'b'], [3, 'c']]}] -> [{'result': [[2, 'a'], [1, 'b'], [3, 'c']]}]
Match: True
---
Testing task 20/20: 24 game
Task: 24 game
GT1: [{'X': 24}] -> [{'x': 24}]
Result1: [{'X': 24}] -> [{'x': 24}]
Match: True
---
Test results saved to prolog_test_results.csv

Summary:
Total tasks: 20
Passed both tests: 20 (100.00%)
Passed one test: 0 (0.00%)
Failed both tests: 20 (100.00%)

Warning: /tmp/tmpds0lghpx.pl:2:
Warning:    Redefined static procedure fib/2
Warning:    Previously defined at /tmp/tmphwi41jm8.pl:2
Warning: /tmp/tmpgi_b03v1.pl:2:
Warning:    Redefined static procedure fib/2
Warning:    Previously defined at /tmp/tmphwi41jm8.pl:2
Warning: /tmp/tmpywa42pn_.pl:1:
Warning:    Redefined static procedure primes/2
Warning:    Previously defined at /tmp/tmpak3iib__.pl:1
Warning: /tmp/tmpywa42pn_.pl:3:
Warning:    Redefined static procedure sieve/2
Warning:    Previously defined at /tmp/tmpak3iib__.pl:3
Warning: /tmp/tmpywa42pn_.pl:7:
Warning:    Redefined static procedure filter/4
Warning:    Previously defined at /tmp/tmpak3iib__.pl:7
Warning: /tmp/tmp5shnu9jc.pl:1:
Warning:    Redefined static procedure primes/2
Warning:    Previously defined at /tmp/tmpak3iib__.pl:1
Warning: /tmp/tmp5shnu9jc.pl:3:
Warning:    Redefined static procedure sieve/2
Warning:    Previously defined at /tmp/tmpak3iib__.pl:3
Warning: /tmp/tmp5shnu9jc.pl:7:
Warning:    Redefined static procedure filter/4
Warning:    Previously defined at /tmp/tmpak3iib__.pl:7
Warning: /tmp/tmpf98tl8po.pl:1:
Warning:    Redefined static procedure qsort/2
Warning:    Previously defined at /tmp/tmpexm4gbqq.pl:1
Warning: /tmp/tmpf98tl8po.pl:5:
Warning:    Redefined static procedure splitBy/4
Warning:    Previously defined at /tmp/tmpexm4gbqq.pl:5
Warning: /tmp/tmpgax9llir.pl:1:
Warning:    Redefined static procedure qsort/2
Warning:    Previously defined at /tmp/tmpexm4gbqq.pl:1
Warning: /tmp/tmpgax9llir.pl:5:
Warning:    Redefined static procedure splitBy/4
Warning:    Previously defined at /tmp/tmpexm4gbqq.pl:5
Warning: /tmp/tmpx72l5b8w.pl:2:
Warning:    Redefined static procedure bin_search/3
Warning:    Previously defined at /tmp/tmp9wzqtx_3.pl:2
Warning: /tmp/tmpx72l5b8w.pl:6:
Warning:    Redefined static procedure bin_search_inner/5
Warning:    Previously defined at /tmp/tmp9wzqtx_3.pl:6
Warning: /tmp/tmpkjqdacnv.pl:2:
Warning:    Redefined static procedure bin_search/3
Warning:    Previously defined at /tmp/tmp9wzqtx_3.pl:2
Warning: /tmp/tmpkjqdacnv.pl:6:
Warning:    Redefined static procedure bin_search_inner/5
Warning:    Previously defined at /tmp/tmp9wzqtx_3.pl:6
Warning: /tmp/tmpg77kcinx.pl:1:
Warning:    Redefined static procedure gcd/3
Warning:    Previously defined at /tmp/tmpa1owryso.pl:1
Warning: /tmp/tmp1lot_823.pl:1:
Warning:    Redefined static procedure gcd/3
Warning:    Previously defined at /tmp/tmpa1owryso.pl:1
Warning: /tmp/tmp1mkz1fcr.pl:1:
Warning:    Redefined static procedure fact/2
Warning:    Previously defined at /tmp/tmpau1iy7uf.pl:1
Warning: /tmp/tmpuzt1z8xi.pl:1:
Warning:    Redefined static procedure fact/2
Warning:    Previously defined at /tmp/tmpau1iy7uf.pl:1
Warning: /tmp/tmpz56ncdhg.pl:1:
Warning:    Redefined static procedure hanoi/1
Warning:    Previously defined at /tmp/tmp6mfydsgd.pl:1
Warning: /tmp/tmpz56ncdhg.pl:2:
Warning:    Redefined static procedure move/4
Warning:    Previously defined at /tmp/tmp6mfydsgd.pl:2
Warning: /tmp/tmpz56ncdhg.pl:8:
Warning:    Redefined static procedure inform/2
Warning:    Previously defined at /tmp/tmp6mfydsgd.pl:8
Warning: /tmp/tmpieligofm.pl:1:
Warning:    Redefined static procedure hanoi/1
Warning:    Previously defined at /tmp/tmp6mfydsgd.pl:1
Warning: /tmp/tmpieligofm.pl:2:
Warning:    Redefined static procedure move/4
Warning:    Previously defined at /tmp/tmp6mfydsgd.pl:2
Warning: /tmp/tmpieligofm.pl:8:
Warning:    Redefined static procedure inform/2
Warning:    Previously defined at /tmp/tmp6mfydsgd.pl:8
Warning: /tmp/tmpmdqf7gxf.pl:1:
Warning:    Redefined static procedure palindrome/1
Warning:    Previously defined at /tmp/tmpi_10b0ca.pl:1
Warning: /tmp/tmpxpa5s2hn.pl:1:
Warning:    Redefined static procedure palindrome/1
Warning:    Previously defined at /tmp/tmpi_10b0ca.pl:1
Warning: /tmp/tmpb7vorsuo.pl:1:
Warning:    Redefined static procedure prime_decomp/2
Warning:    Previously defined at /tmp/tmpe6wiemmt.pl:1
Warning: /tmp/tmpb7vorsuo.pl:4:
Warning:    Redefined static procedure prime_decomp_1/5
Warning:    Previously defined at /tmp/tmpe6wiemmt.pl:4
Warning: /tmp/tmpb7vorsuo.pl:20:
Warning:    Redefined static procedure prime_decomp_2/5
Warning:    Previously defined at /tmp/tmpe6wiemmt.pl:20
Warning: /tmp/tmp738xat9_.pl:1:
Warning:    Redefined static procedure prime_decomp/2
Warning:    Previously defined at /tmp/tmpe6wiemmt.pl:1
Warning: /tmp/tmp738xat9_.pl:4:
Warning:    Redefined static procedure prime_decomp_1/5
Warning:    Previously defined at /tmp/tmpe6wiemmt.pl:4
Warning: /tmp/tmp738xat9_.pl:20:
Warning:    Redefined static procedure prime_decomp_2/5
Warning:    Previously defined at /tmp/tmpe6wiemmt.pl:20
Warning: /tmp/tmp4euyu60a.pl:4:
Warning:    Redefined static procedure edge/3
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:4
Warning: /tmp/tmp4euyu60a.pl:14:
Warning:    Redefined static procedure path/3
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:14
Warning: /tmp/tmp4euyu60a.pl:17:
Warning:    Singleton variables: [T]
Warning: /tmp/tmp4euyu60a.pl:17:
Warning:    Redefined static procedure shorterPath/2
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:17
Warning: /tmp/tmp4euyu60a.pl:25:
Warning:    Redefined static procedure traverse/3
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:25
Warning: /tmp/tmp4euyu60a.pl:31:
Warning:    Redefined static procedure traverse/1
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:31
Warning: /tmp/tmp4euyu60a.pl:36:
Warning:    Redefined static procedure go/2
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:36
Warning: /tmp/tmpu10a55i3.pl:4:
Warning:    Redefined static procedure edge/3
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:4
Warning: /tmp/tmpu10a55i3.pl:14:
Warning:    Redefined static procedure path/3
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:14
Warning: /tmp/tmpu10a55i3.pl:17:
Warning:    Singleton variables: [T]
Warning: /tmp/tmpu10a55i3.pl:17:
Warning:    Redefined static procedure shorterPath/2
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:17
Warning: /tmp/tmpu10a55i3.pl:25:
Warning:    Redefined static procedure traverse/3
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:25
Warning: /tmp/tmpu10a55i3.pl:31:
Warning:    Redefined static procedure traverse/1
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:31
Warning: /tmp/tmpu10a55i3.pl:36:
Warning:    Redefined static procedure go/2
Warning:    Previously defined at /tmp/tmpheizsbgt.pl:36
Warning: /tmp/tmpv8yetbzm.pl:1:
Warning:    Redefined static procedure levenshtein/3
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:1
Warning: /tmp/tmpv8yetbzm.pl:20:
Warning:    Redefined static procedure work_on_T/4
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:20
Warning: /tmp/tmpv8yetbzm.pl:25:
Warning:    Redefined static procedure work_on_S/5
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:25
Warning: /tmp/tmpv8yetbzm.pl:57:
Warning:    Redefined static procedure init/2
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:57
Warning: /tmp/tmpv8yetbzm.pl:60:
Warning:    Redefined static procedure init_n/2
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:60
Warning: /tmp/tmpsifom_sk.pl:1:
Warning:    Redefined static procedure levenshtein/3
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:1
Warning: /tmp/tmpsifom_sk.pl:20:
Warning:    Redefined static procedure work_on_T/4
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:20
Warning: /tmp/tmpsifom_sk.pl:25:
Warning:    Redefined static procedure work_on_S/5
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:25
Warning: /tmp/tmpsifom_sk.pl:57:
Warning:    Redefined static procedure init/2
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:57
Warning: /tmp/tmpsifom_sk.pl:60:
Warning:    Redefined static procedure init_n/2
Warning:    Previously defined at /tmp/tmpdf1sl84o.pl:60
Warning: /tmp/tmps6hn3plw.pl:1:
Warning:    Redefined static procedure solution/1
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:1
Warning: /tmp/tmps6hn3plw.pl:6:
Warning:    Redefined static procedure noattack/2
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:6
Warning: /tmp/tmps6hn3plw.pl:12:
Warning:    Singleton variables: [Rest]
Warning: /tmp/tmps6hn3plw.pl:12:
Warning:    Redefined static procedure member/2
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:12
Warning: /tmp/tmps6hn3plw.pl:13:
Warning:    Singleton variables: [First]
Warning: /tmp/tmps6hn3plw.pl:15:
Warning:    Singleton variables: [Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8]
Warning: /tmp/tmps6hn3plw.pl:15:
Warning:    Redefined static procedure template/1
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:15
Warning: /tmp/tmpsp2bv_dk.pl:1:
Warning:    Redefined static procedure solution/1
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:1
Warning: /tmp/tmpsp2bv_dk.pl:6:
Warning:    Redefined static procedure noattack/2
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:6
Warning: /tmp/tmpsp2bv_dk.pl:12:
Warning:    Singleton variables: [Rest]
Warning: /tmp/tmpsp2bv_dk.pl:12:
Warning:    Redefined static procedure member/2
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:12
Warning: /tmp/tmpsp2bv_dk.pl:13:
Warning:    Singleton variables: [First]
Warning: /tmp/tmpsp2bv_dk.pl:15:
Warning:    Singleton variables: [Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8]
Warning: /tmp/tmpsp2bv_dk.pl:15:
Warning:    Redefined static procedure template/1
Warning:    Previously defined at /tmp/tmpehgv38x8.pl:15
Warning: /tmp/tmpwjjgf2_3.pl:2:
Warning:    Redefined static procedure ack/3
Warning:    Previously defined at /tmp/tmpbbt8nboo.pl:2
Warning: /tmp/tmpiwv781sn.pl:2:
Warning:    Redefined static procedure ack/3
Warning:    Previously defined at /tmp/tmpbbt8nboo.pl:2
Warning: /tmp/tmpcuq3_2kq.pl:1:
Warning:    Redefined static procedure rosetta_brackets/0
Warning:    Previously defined at /tmp/tmpqcvr63yg.pl:1
Warning: /tmp/tmpcuq3_2kq.pl:10:
Warning:    Redefined static procedure balanced_brackets/0
Warning:    Previously defined at /tmp/tmpqcvr63yg.pl:10
Warning: /tmp/tmpcuq3_2kq.pl:21:
Warning:    Redefined static procedure test_brackets/1
Warning:    Previously defined at /tmp/tmpqcvr63yg.pl:21
Warning: /tmp/tmpcuq3_2kq.pl:30:
Warning:    Redefined static procedure balanced_brackets/2
Warning:    Previously defined at /tmp/tmpqcvr63yg.pl:30
Warning: /tmp/tmpcuq3_2kq.pl:43:
Warning:    Redefined static procedure gen_bracket/3
Warning:    Previously defined at /tmp/tmpqcvr63yg.pl:43
Warning: /tmp/tmpcuq3_2kq.pl:51:
Warning:    Redefined static procedure bracket/3
Warning:    Previously defined at /tmp/tmpqcvr63yg.pl:51
Warning: /tmp/tmphmp_jb57.pl:1:
Warning:    Redefined static procedure rosetta_brackets/0
Warning:    Previously defined at /tmp/tmpcuq3_2kq.pl:1
Warning: /tmp/tmphmp_jb57.pl:10:
Warning:    Redefined static procedure balanced_brackets/0
Warning:    Previously defined at /tmp/tmpcuq3_2kq.pl:10
Warning: /tmp/tmphmp_jb57.pl:21:
Warning:    Redefined static procedure test_brackets/1
Warning:    Previously defined at /tmp/tmpcuq3_2kq.pl:21
Warning: /tmp/tmphmp_jb57.pl:30:
Warning:    Redefined static procedure balanced_brackets/2
Warning:    Previously defined at /tmp/tmpcuq3_2kq.pl:30
Warning: /tmp/tmphmp_jb57.pl:43:
Warning:    Redefined static procedure gen_bracket/3
Warning:    Previously defined at /tmp/tmpcuq3_2kq.pl:43
Warning: /tmp/tmphmp_jb57.pl:51:
Warning:    Redefined static procedure bracket/3
Warning:    Previously defined at /tmp/tmpcuq3_2kq.pl:51
Warning: /tmp/tmp3idhh8k3.pl:2:
Warning:    Redefined static procedure knight/2
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:2
Warning: /tmp/tmp3idhh8k3.pl:7:
Warning:    Redefined static procedure knight/6
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:7
Warning: /tmp/tmp3idhh8k3.pl:25:
Warning:    Redefined static procedure move/5
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:25
Warning: /tmp/tmp3idhh8k3.pl:30:
Warning:    Redefined static procedure best_move/4
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:30
Warning: /tmp/tmp3idhh8k3.pl:49:
Warning:    Redefined static procedure possible_move/3
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:49
Warning: /tmp/tmp3idhh8k3.pl:58:
Warning:    Redefined static procedure format_solution/3
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:58
Warning: /tmp/tmp3idhh8k3.pl:61:
Warning:    Redefined static procedure format_solution/5
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:61
Warning: /tmp/tmpp_bcjmh4.pl:2:
Warning:    Redefined static procedure knight/2
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:2
Warning: /tmp/tmpp_bcjmh4.pl:7:
Warning:    Redefined static procedure knight/6
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:7
Warning: /tmp/tmpp_bcjmh4.pl:25:
Warning:    Redefined static procedure move/5
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:25
Warning: /tmp/tmpp_bcjmh4.pl:30:
Warning:    Redefined static procedure best_move/4
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:30
Warning: /tmp/tmpp_bcjmh4.pl:49:
Warning:    Redefined static procedure possible_move/3
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:49
Warning: /tmp/tmpp_bcjmh4.pl:58:
Warning:    Redefined static procedure format_solution/3
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:58
Warning: /tmp/tmpp_bcjmh4.pl:61:
Warning:    Redefined static procedure format_solution/5
Warning:    Previously defined at /tmp/tmp_xwyl6t7.pl:61
Warning: /tmp/tmp2yypnbk6.pl:3:
Warning:    Redefined static procedure my_merge_sort/2
Warning:    Previously defined at /tmp/tmp43hjvbru.pl:3
Warning: /tmp/tmp2yypnbk6.pl:13:
Warning:    Redefined static procedure split/3
Warning:    Previously defined at /tmp/tmp43hjvbru.pl:13
Warning: /tmp/tmp2yypnbk6.pl:19:
Warning:    Redefined static procedure merge/3
Warning:    Previously defined at /tmp/tmp43hjvbru.pl:19
Warning: /tmp/tmp0j_wtf_s.pl:3:
Warning:    Redefined static procedure my_merge_sort/2
Warning:    Previously defined at /tmp/tmp43hjvbru.pl:3
Warning: /tmp/tmp0j_wtf_s.pl:13:
Warning:    Redefined static procedure split/3
Warning:    Previously defined at /tmp/tmp43hjvbru.pl:13
Warning: /tmp/tmp0j_wtf_s.pl:19:
Warning:    Redefined static procedure merge/3
Warning:    Previously defined at /tmp/tmp43hjvbru.pl:19
Warning: /tmp/tmp77047edo.pl:1:
Warning:    Redefined static procedure decode_digit/2
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:1
Warning: /tmp/tmp77047edo.pl:9:
Warning:    Redefined static procedure decode_string/4
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:9
Warning: /tmp/tmp77047edo.pl:23:
Warning:    Redefined static procedure decode_string/2
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:23
Warning: /tmp/tmp77047edo.pl:29:
Warning:    Redefined static procedure test/0
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:29
Warning: /tmp/tmpn0nt1u02.pl:1:
Warning:    Redefined static procedure decode_digit/2
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:1
Warning: /tmp/tmpn0nt1u02.pl:9:
Warning:    Redefined static procedure decode_string/4
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:9
Warning: /tmp/tmpn0nt1u02.pl:23:
Warning:    Redefined static procedure decode_string/2
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:23
Warning: /tmp/tmpn0nt1u02.pl:29:
Warning:    Redefined static procedure test/0
Warning:    Previously defined at /tmp/tmp4nma0mpc.pl:29
Warning: /tmp/tmpkgn8uqm3.pl:1:
Warning:    Redefined static procedure lcs/3
Warning:    Previously defined at /tmp/tmp12s7ah5c.pl:1
Warning: /tmp/tmpkgn8uqm3.pl:12:
Warning:    Redefined static procedure longest/3
Warning:    Previously defined at /tmp/tmp12s7ah5c.pl:12
Warning: /tmp/tmpatg34lk6.pl:1:
Warning:    Redefined static procedure lcs/3
Warning:    Previously defined at /tmp/tmp12s7ah5c.pl:1
Warning: /tmp/tmpatg34lk6.pl:12:
Warning:    Redefined static procedure longest/3
Warning:    Previously defined at /tmp/tmp12s7ah5c.pl:12
Warning: /tmp/tmp13vkxqxm.pl:1:
Warning:    Redefined static procedure huffman/0
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:1
Warning: /tmp/tmp13vkxqxm.pl:13:
Warning:    Redefined static procedure build_tree/2
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:13
Warning: /tmp/tmp13vkxqxm.pl:18:
Warning:    Redefined static procedure coding/3
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:18
Warning: /tmp/tmp13vkxqxm.pl:25:
Warning:    Redefined static procedure leaf_coding/3
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:25
Warning: /tmp/tmp13vkxqxm.pl:29:
Warning:    Redefined static procedure is_node/1
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:29
Warning: /tmp/tmp13vkxqxm.pl:31:
Warning:    Redefined static procedure print_code/1
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:31
Warning: /tmp/tmp13vkxqxm.pl:36:
Warning:    Redefined static procedure packList/2
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:36
Warning: /tmp/tmp13vkxqxm.pl:42:
Warning:    Redefined static procedure run/4
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:42
Warning: /tmp/tmp8yvgh09p.pl:1:
Warning:    Redefined static procedure huffman/0
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:1
Warning: /tmp/tmp8yvgh09p.pl:13:
Warning:    Redefined static procedure build_tree/2
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:13
Warning: /tmp/tmp8yvgh09p.pl:18:
Warning:    Redefined static procedure coding/3
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:18
Warning: /tmp/tmp8yvgh09p.pl:25:
Warning:    Redefined static procedure leaf_coding/3
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:25
Warning: /tmp/tmp8yvgh09p.pl:29:
Warning:    Redefined static procedure is_node/1
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:29
Warning: /tmp/tmp8yvgh09p.pl:31:
Warning:    Redefined static procedure print_code/1
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:31
Warning: /tmp/tmp8yvgh09p.pl:36:
Warning:    Redefined static procedure packList/2
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:36
Warning: /tmp/tmp8yvgh09p.pl:42:
Warning:    Redefined static procedure run/4
Warning:    Previously defined at /tmp/tmpvmemihvl.pl:42
Warning: /tmp/tmp0_q85_rt.pl:2:
Warning:    Redefined static procedure answer/1
Warning:    Previously defined at /tmp/tmp_n32d480.pl:2
Warning: /tmp/tmp0_q85_rt.pl:3:
Warning:    Redefined static procedure play/0
Warning:    Previously defined at /tmp/tmp_n32d480.pl:3
Warning: /tmp/tmp0_q85_rt.pl:5:
Warning:    Redefined static procedure round/0
Warning:    Previously defined at /tmp/tmp_n32d480.pl:5
Warning: /tmp/tmp0_q85_rt.pl:11:
Warning:    Redefined static procedure prompt/1
Warning:    Previously defined at /tmp/tmp_n32d480.pl:11
Warning: /tmp/tmp0_q85_rt.pl:15:
Warning:    Redefined static procedure parse/4
Warning:    Previously defined at /tmp/tmp_n32d480.pl:15
Warning: /tmp/tmp0_q85_rt.pl:25:
Warning:    Redefined static procedure get_line/1
Warning:    Previously defined at /tmp/tmp_n32d480.pl:25
Warning: /tmp/tmp0_q85_rt.pl:28:
Warning:    Redefined static procedure main/0
Warning:    Previously defined at /tmp/tmp_n32d480.pl:28
ERROR: /tmp/tmp0_q85_rt.pl:1: Initialization goal raised exception:
ERROR: main/0: Unknown procedure: randomize/0
Warning: /tmp/tmpqy06ptqr.pl:2:
Warning:    Redefined static procedure answer/1
Warning:    Previously defined at /tmp/tmp0_q85_rt.pl:2
Warning: /tmp/tmpqy06ptqr.pl:3:
Warning:    Redefined static procedure play/0
Warning:    Previously defined at /tmp/tmp0_q85_rt.pl:3
Warning: /tmp/tmpqy06ptqr.pl:5:
Warning:    Redefined static procedure round/0
Warning:    Previously defined at /tmp/tmp0_q85_rt.pl:5
Warning: /tmp/tmpqy06ptqr.pl:11:
Warning:    Redefined static procedure prompt/1
Warning:    Previously defined at /tmp/tmp0_q85_rt.pl:11
Warning: /tmp/tmpqy06ptqr.pl:15:
Warning:    Redefined static procedure parse/4
Warning:    Previously defined at /tmp/tmp0_q85_rt.pl:15
Warning: /tmp/tmpqy06ptqr.pl:25: